### PR TITLE
Creation of README.md

### PR DESCRIPTION
**Pull request by ndufreche**
I add the introduction day 1 and the manual installation mode for start from a custom day.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
:+1: 

Squash your commits dude :)

**Comment by ndufreche** [comment]
I let some time for @backbee/core-team to review this PR

**Comment by mickaelandrieu** [comment]
ping @backbee/core-team this don't need too much review here ;)

**Comment by mickaelandrieu** [comment]
no one contest, it's ok to me.

Thanks @ndufreche

**Pull request merged**
